name: Cron

permissions:
  contents: write
  pull-requests: write
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8 #install the python needed
    - name: run
      run: |
        npm run init
        npm run main
        git status
    - name: Open PR
      uses: peter-evans/create-pull-request@v4
      with:
        title: Automatic Update